; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -O3 -verify-machineinstrs -mattr=+sve -force-streaming-compatible | FileCheck %s
; RUN: llc < %s -O3 -verify-machineinstrs -force-streaming-compatible | FileCheck %s --check-prefix=NONEON-NOSVE

target triple = "aarch64-unknown-linux"

define void @foo(ptr %s) {
; CHECK-LABEL: foo:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    index z0.d, #1, #-1
; CHECK-NEXT:    str q0, [x0]
; CHECK-NEXT:    ret
;
; NONEON-NOSVE-LABEL: foo:
; NONEON-NOSVE:       // %bb.0: // %entry
; NONEON-NOSVE-NEXT:    mov w8, #1 // =0x1
; NONEON-NOSVE-NEXT:    stp x8, xzr, [x0]
; NONEON-NOSVE-NEXT:    ret
entry:
  store <2 x i64> <i64 1, i64 0>, ptr %s, align 8
  ret void
}

define void @foo2(ptr %s) {
; CHECK-LABEL: foo2:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    mov w8, #10293 // =0x2835
; CHECK-NEXT:    mov w9, #2329 // =0x919
; CHECK-NEXT:    stp x9, x8, [x0]
; CHECK-NEXT:    ret
;
; NONEON-NOSVE-LABEL: foo2:
; NONEON-NOSVE:       // %bb.0: // %entry
; NONEON-NOSVE-NEXT:    mov w8, #10293 // =0x2835
; NONEON-NOSVE-NEXT:    mov w9, #2329 // =0x919
; NONEON-NOSVE-NEXT:    stp x9, x8, [x0]
; NONEON-NOSVE-NEXT:    ret
entry:
  store <2 x i64> <i64 2329, i64 10293>, ptr %s, align 8
  ret void
}

define void @foo3(ptr %s) {
; CHECK-LABEL: foo3:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    mov w8, #39997 // =0x9c3d
; CHECK-NEXT:    index z0.d, #3, x8
; CHECK-NEXT:    str q0, [x0]
; CHECK-NEXT:    ret
;
; NONEON-NOSVE-LABEL: foo3:
; NONEON-NOSVE:       // %bb.0: // %entry
; NONEON-NOSVE-NEXT:    mov w8, #40000 // =0x9c40
; NONEON-NOSVE-NEXT:    mov w9, #3 // =0x3
; NONEON-NOSVE-NEXT:    stp x9, x8, [x0]
; NONEON-NOSVE-NEXT:    ret
entry:
  store <2 x i64> <i64 3, i64 40000>, ptr %s, align 8
  ret void
}
