; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -O3 -verify-machineinstrs -mtriple=aarch64-unknown-linux | FileCheck %s

define void @foo(ptr %s) {
; CHECK-LABEL: foo:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    mov x8, #1 // =0x1
; CHECK-NEXT:    stp x8, xzr, [x0]
; CHECK-NEXT:    ret
entry:
  store <2 x i64> <i64 1, i64 0>, ptr %s, align 8
  ret void
}

define void @foo2(ptr %s) {
; CHECK-LABEL: foo2:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    mov x8, #10293 // =0x2835
; CHECK-NEXT:    mov x9, #2329 // =0x919
; CHECK-NEXT:    stp x9, x8, [x0]
; CHECK-NEXT:    ret
entry:
  store <2 x i64> <i64 2329, i64 10293>, ptr %s, align 8
  ret void
}
