; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt < %s -passes=instrumentor -S | FileCheck %s
define i32 @foo(i1 %c) {
; CHECK-LABEL: define i32 @foo(
; CHECK-SAME: i1 [[C:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = zext i1 [[C]] to i8
; CHECK-NEXT:    call void @__instrumentor_pre_branch(i8 1, i8 [[TMP0]], i64 2)
; CHECK-NEXT:    br i1 [[C]], label %[[A:.*]], label %[[B:.*]]
; CHECK:       [[A]]:
; CHECK-NEXT:    ret i32 0
; CHECK:       [[B]]:
; CHECK-NEXT:    call void @__instrumentor_pre_branch(i8 0, i8 1, i64 1)
; CHECK-NEXT:    br label %[[D:.*]]
; CHECK:       [[D]]:
; CHECK-NEXT:    ret i32 1
;
entry:
  br i1 %c, label %a, label %b
a:
  ret i32 0
b:
  br label %d
d:
  ret i32 1
}
